# store the stream client lb ipv4 and ipv6 for message broker (kafka)
streamServers:
  host: cssvlab01.uwb.edu
  ip: 10.158.82.6 
  port: 9092

# systemd resolved internally forward to physical netdev / wire for upstream resolver, attached kernel egress datapath ebpf filters 
# note if using stub resolver this must be disabled due to hard dev xmit on loopback and internal easr-west traffic over links in kernel forward to physical wire by resolved
dnsResolver:
  - host: cssvlab08.uwb.edu
    ip: 10.158.82.55
    port: 53 
  

# store the metric server (prmetheus exporters running to scrape info) ipv4 and ipv6 
metricServer:
  host: cssvlab01.uwb.edu
  ip: 10.158.82.6 
  port: 9090


# service grafnaa viz exporter for dashboard UI
grafanaServer: 
  host: cssvlab01.uwb.edu
  ip: 10.158.82.6  
  port: 3000
  
# prometheus custom local metrics exporter 
metricsExporter:
  port: 3232 # host is the local node exporting metrics whcih this centralized metric server can scrape 
  ip: 0.0.0.0 # service local phsical inet net_device link bind from kernel 

inference:
  ingressSock: "/run/dnsobelisk/onnx-inference-in.sock"
  egressSock: "/run/dnsobelisk/onnx-inference-out.sock"

disableExporters:
  streaming: false
  metrics:: false

rlimitConfig:
  tb:
    maxTokens: 10000


agent:
  agentModeAggressive: false # for DNS over UDP kernel eBPF aggresively redirect packet to userspace, for deep inference ensuring no exfiltrated packet over DNS leaves the endpoint 
  agentModeIsolated: true # assumes this agent is alone runnin at endpoint and not connected to control plane, the agent does not get any updates or malicious stream process from control plane 
  # the required store time in sec for the caceh to stay hot and prevent the c2 implant bruteforce and bring down the agent 
  ingressMaliciousCacheTTL: 50 
  egressMaliciousCacheTTL: 80
  globalMaliciousprocessCacheTTl: 15

# Add the tb volume config for volume based rate limit over egress tc in kernel 

enhancedFeatures:
  l3: # for l3 filtering to stop exfiltration over other protocols which c2 server remote server ip can be used to exftract data via other tunnel protocols 
    enabledL3v4Filtering: true 
    enabledL3v6Filtering: true 
  dns:
    enableNxFloodPrevention: false 
    enableIngressSniff: true 
    enabledTbRlimit: false
    enabledVolumeRlimit: false
    
    enabledPassiveEgressEnhancedTCPDPI: true # works as a  passive sniffer over TCP for filtering ans seuciryt malicious domains 
