syntax = "proto3";

package exfil_kernel;

option go_package = "github.com/Synarcs/Data-Exfiltration-Security-Framework/exfil_sec_api;exfil_sec_api";
// the proto is initially written for multi-layer security with control plane verifying progs, and signatures for the eBPF progs at the endpoint over the data plane

enum DNS_MALICIOUS_FLAGS {
    MALICIOUS  = 0;
    SUSPICIOUS = 1;
}

enum KERNEL_KEYRING_OPS_TYPES {
    KEYCTL_REVOKE = 0;
    KEYCTL_REJECT = 1;
    KEYCTL_CLEAR = 2;
}

enum KERNEL_KEYRING_TYPES {
    USER = 0;
    SESSION = 1;
    PROCESS = 2;
}

enum KERNEL_KEYRING_KEY_TYPES { 
    K_USER = 0;
    K_LOGONG = 1;
    K_ASYMMETRIC = 2;
}

message ExfilDomains {
    string domain = 1;
    string tld = 2;
    int64 totalLength = 3;
    repeated uint32 featureVectors = 4;
    map<string, DNS_MALICIOUS_FLAGS> status = 5;
};

message ElfSignatureRequest {
    bytes eBPFProgramPayload = 1;
}

message ElfSignatureResponse { 
    bytes signature = 1;
    bytes publicKey = 2;
    bytes signatureHash = 3;
}

message AgentKernelKeyringControllerCommandRequest {
    repeated KERNEL_KEYRING_OPS_TYPES cmd = 1;
    repeated KERNEL_KEYRING_TYPES ringTypes = 2;
    repeated KERNEL_KEYRING_KEY_TYPES keyTypes = 3;
}

message AgentKernelKeyringControllerCommandResponse {
    repeated bool response = 1;
}

message ExfillSecurityLengthLimits { 
    map<int32, int32> domainrangeExfilLimits = 1;
}

message ExfilDomainsLength {
    int64 len = 1;
}

service NodeAgentFeatureService {
    rpc GetExfilDomains(ExfilDomains) returns (stream ExfilDomains);
    rpc GenExfilDomainsLength(ExfilDomains) returns (ExfilDomainsLength);
    rpc BidirstreamLimits(stream ExfillSecurityLengthLimits) returns (stream ExfillSecurityLengthLimits);
};

service NodeAgentCryptoService {
    rpc EBPFElfSignature(ElfSignatureRequest) returns (ElfSignatureResponse);
    rpc EBPFKeyringController(AgentKernelKeyringControllerCommandRequest) returns (AgentKernelKeyringControllerCommandResponse);
}
