// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: exfil_sec.proto

package Data_Exfiltration_Security_Framework

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	NodeAgentService_GetExfilDomains_FullMethodName       = "/exfil_kernel.NodeAgentService/GetExfilDomains"
	NodeAgentService_GenExfilDomainsLength_FullMethodName = "/exfil_kernel.NodeAgentService/GenExfilDomainsLength"
	NodeAgentService_BidirstreamLimits_FullMethodName     = "/exfil_kernel.NodeAgentService/BidirstreamLimits"
)

// NodeAgentServiceClient is the client API for NodeAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAgentServiceClient interface {
	GetExfilDomains(ctx context.Context, in *ExfilDomains, opts ...grpc.CallOption) (NodeAgentService_GetExfilDomainsClient, error)
	GenExfilDomainsLength(ctx context.Context, in *ExfilDomains, opts ...grpc.CallOption) (*ExfilDomainsLength, error)
	BidirstreamLimits(ctx context.Context, opts ...grpc.CallOption) (NodeAgentService_BidirstreamLimitsClient, error)
}

type nodeAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentServiceClient(cc grpc.ClientConnInterface) NodeAgentServiceClient {
	return &nodeAgentServiceClient{cc}
}

func (c *nodeAgentServiceClient) GetExfilDomains(ctx context.Context, in *ExfilDomains, opts ...grpc.CallOption) (NodeAgentService_GetExfilDomainsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[0], NodeAgentService_GetExfilDomains_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentServiceGetExfilDomainsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeAgentService_GetExfilDomainsClient interface {
	Recv() (*ExfilDomains, error)
	grpc.ClientStream
}

type nodeAgentServiceGetExfilDomainsClient struct {
	grpc.ClientStream
}

func (x *nodeAgentServiceGetExfilDomainsClient) Recv() (*ExfilDomains, error) {
	m := new(ExfilDomains)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeAgentServiceClient) GenExfilDomainsLength(ctx context.Context, in *ExfilDomains, opts ...grpc.CallOption) (*ExfilDomainsLength, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExfilDomainsLength)
	err := c.cc.Invoke(ctx, NodeAgentService_GenExfilDomainsLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) BidirstreamLimits(ctx context.Context, opts ...grpc.CallOption) (NodeAgentService_BidirstreamLimitsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[1], NodeAgentService_BidirstreamLimits_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentServiceBidirstreamLimitsClient{ClientStream: stream}
	return x, nil
}

type NodeAgentService_BidirstreamLimitsClient interface {
	Send(*ExfillSecurityLengthLimits) error
	Recv() (*ExfillSecurityLengthLimits, error)
	grpc.ClientStream
}

type nodeAgentServiceBidirstreamLimitsClient struct {
	grpc.ClientStream
}

func (x *nodeAgentServiceBidirstreamLimitsClient) Send(m *ExfillSecurityLengthLimits) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeAgentServiceBidirstreamLimitsClient) Recv() (*ExfillSecurityLengthLimits, error) {
	m := new(ExfillSecurityLengthLimits)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeAgentServiceServer is the server API for NodeAgentService service.
// All implementations should embed UnimplementedNodeAgentServiceServer
// for forward compatibility
type NodeAgentServiceServer interface {
	GetExfilDomains(*ExfilDomains, NodeAgentService_GetExfilDomainsServer) error
	GenExfilDomainsLength(context.Context, *ExfilDomains) (*ExfilDomainsLength, error)
	BidirstreamLimits(NodeAgentService_BidirstreamLimitsServer) error
}

// UnimplementedNodeAgentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedNodeAgentServiceServer struct {
}

func (UnimplementedNodeAgentServiceServer) GetExfilDomains(*ExfilDomains, NodeAgentService_GetExfilDomainsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetExfilDomains not implemented")
}
func (UnimplementedNodeAgentServiceServer) GenExfilDomainsLength(context.Context, *ExfilDomains) (*ExfilDomainsLength, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenExfilDomainsLength not implemented")
}
func (UnimplementedNodeAgentServiceServer) BidirstreamLimits(NodeAgentService_BidirstreamLimitsServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirstreamLimits not implemented")
}

// UnsafeNodeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServiceServer will
// result in compilation errors.
type UnsafeNodeAgentServiceServer interface {
	mustEmbedUnimplementedNodeAgentServiceServer()
}

func RegisterNodeAgentServiceServer(s grpc.ServiceRegistrar, srv NodeAgentServiceServer) {
	s.RegisterService(&NodeAgentService_ServiceDesc, srv)
}

func _NodeAgentService_GetExfilDomains_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExfilDomains)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServiceServer).GetExfilDomains(m, &nodeAgentServiceGetExfilDomainsServer{ServerStream: stream})
}

type NodeAgentService_GetExfilDomainsServer interface {
	Send(*ExfilDomains) error
	grpc.ServerStream
}

type nodeAgentServiceGetExfilDomainsServer struct {
	grpc.ServerStream
}

func (x *nodeAgentServiceGetExfilDomainsServer) Send(m *ExfilDomains) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeAgentService_GenExfilDomainsLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExfilDomains)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GenExfilDomainsLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GenExfilDomainsLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GenExfilDomainsLength(ctx, req.(*ExfilDomains))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_BidirstreamLimits_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).BidirstreamLimits(&nodeAgentServiceBidirstreamLimitsServer{ServerStream: stream})
}

type NodeAgentService_BidirstreamLimitsServer interface {
	Send(*ExfillSecurityLengthLimits) error
	Recv() (*ExfillSecurityLengthLimits, error)
	grpc.ServerStream
}

type nodeAgentServiceBidirstreamLimitsServer struct {
	grpc.ServerStream
}

func (x *nodeAgentServiceBidirstreamLimitsServer) Send(m *ExfillSecurityLengthLimits) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeAgentServiceBidirstreamLimitsServer) Recv() (*ExfillSecurityLengthLimits, error) {
	m := new(ExfillSecurityLengthLimits)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeAgentService_ServiceDesc is the grpc.ServiceDesc for NodeAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exfil_kernel.NodeAgentService",
	HandlerType: (*NodeAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenExfilDomainsLength",
			Handler:    _NodeAgentService_GenExfilDomainsLength_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetExfilDomains",
			Handler:       _NodeAgentService_GetExfilDomains_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidirstreamLimits",
			Handler:       _NodeAgentService_BidirstreamLimits_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "exfil_sec.proto",
}
