// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: exfil_sec.proto

package Data_Exfiltration_Security_Framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNS_MALICIOUS_FLAGS int32

const (
	DNS_MALICIOUS_FLAGS_MALICIOUS  DNS_MALICIOUS_FLAGS = 0
	DNS_MALICIOUS_FLAGS_SUSPICIOUS DNS_MALICIOUS_FLAGS = 1
)

// Enum value maps for DNS_MALICIOUS_FLAGS.
var (
	DNS_MALICIOUS_FLAGS_name = map[int32]string{
		0: "MALICIOUS",
		1: "SUSPICIOUS",
	}
	DNS_MALICIOUS_FLAGS_value = map[string]int32{
		"MALICIOUS":  0,
		"SUSPICIOUS": 1,
	}
)

func (x DNS_MALICIOUS_FLAGS) Enum() *DNS_MALICIOUS_FLAGS {
	p := new(DNS_MALICIOUS_FLAGS)
	*p = x
	return p
}

func (x DNS_MALICIOUS_FLAGS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DNS_MALICIOUS_FLAGS) Descriptor() protoreflect.EnumDescriptor {
	return file_exfil_sec_proto_enumTypes[0].Descriptor()
}

func (DNS_MALICIOUS_FLAGS) Type() protoreflect.EnumType {
	return &file_exfil_sec_proto_enumTypes[0]
}

func (x DNS_MALICIOUS_FLAGS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DNS_MALICIOUS_FLAGS.Descriptor instead.
func (DNS_MALICIOUS_FLAGS) EnumDescriptor() ([]byte, []int) {
	return file_exfil_sec_proto_rawDescGZIP(), []int{0}
}

type ExfilDomains struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Domain         string                         `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Tld            string                         `protobuf:"bytes,2,opt,name=tld,proto3" json:"tld,omitempty"`
	TotalLength    int64                          `protobuf:"varint,3,opt,name=totalLength,proto3" json:"totalLength,omitempty"`
	FeatureVectors []uint32                       `protobuf:"varint,4,rep,packed,name=featureVectors,proto3" json:"featureVectors,omitempty"`
	Status         map[string]DNS_MALICIOUS_FLAGS `protobuf:"bytes,5,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=exfil_kernel.DNS_MALICIOUS_FLAGS"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExfilDomains) Reset() {
	*x = ExfilDomains{}
	mi := &file_exfil_sec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExfilDomains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExfilDomains) ProtoMessage() {}

func (x *ExfilDomains) ProtoReflect() protoreflect.Message {
	mi := &file_exfil_sec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExfilDomains.ProtoReflect.Descriptor instead.
func (*ExfilDomains) Descriptor() ([]byte, []int) {
	return file_exfil_sec_proto_rawDescGZIP(), []int{0}
}

func (x *ExfilDomains) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ExfilDomains) GetTld() string {
	if x != nil {
		return x.Tld
	}
	return ""
}

func (x *ExfilDomains) GetTotalLength() int64 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

func (x *ExfilDomains) GetFeatureVectors() []uint32 {
	if x != nil {
		return x.FeatureVectors
	}
	return nil
}

func (x *ExfilDomains) GetStatus() map[string]DNS_MALICIOUS_FLAGS {
	if x != nil {
		return x.Status
	}
	return nil
}

type ElfSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	SignatureHash []byte                 `protobuf:"bytes,3,opt,name=signatureHash,proto3" json:"signatureHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElfSignature) Reset() {
	*x = ElfSignature{}
	mi := &file_exfil_sec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElfSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElfSignature) ProtoMessage() {}

func (x *ElfSignature) ProtoReflect() protoreflect.Message {
	mi := &file_exfil_sec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElfSignature.ProtoReflect.Descriptor instead.
func (*ElfSignature) Descriptor() ([]byte, []int) {
	return file_exfil_sec_proto_rawDescGZIP(), []int{1}
}

func (x *ElfSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ElfSignature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ElfSignature) GetSignatureHash() []byte {
	if x != nil {
		return x.SignatureHash
	}
	return nil
}

type ExfillSecurityLengthLimits struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DomainrangeExfilLimits map[int32]int32        `protobuf:"bytes,1,rep,name=domainrangeExfilLimits,proto3" json:"domainrangeExfilLimits,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExfillSecurityLengthLimits) Reset() {
	*x = ExfillSecurityLengthLimits{}
	mi := &file_exfil_sec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExfillSecurityLengthLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExfillSecurityLengthLimits) ProtoMessage() {}

func (x *ExfillSecurityLengthLimits) ProtoReflect() protoreflect.Message {
	mi := &file_exfil_sec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExfillSecurityLengthLimits.ProtoReflect.Descriptor instead.
func (*ExfillSecurityLengthLimits) Descriptor() ([]byte, []int) {
	return file_exfil_sec_proto_rawDescGZIP(), []int{2}
}

func (x *ExfillSecurityLengthLimits) GetDomainrangeExfilLimits() map[int32]int32 {
	if x != nil {
		return x.DomainrangeExfilLimits
	}
	return nil
}

type ExfilDomainsLength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Len           int64                  `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExfilDomainsLength) Reset() {
	*x = ExfilDomainsLength{}
	mi := &file_exfil_sec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExfilDomainsLength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExfilDomainsLength) ProtoMessage() {}

func (x *ExfilDomainsLength) ProtoReflect() protoreflect.Message {
	mi := &file_exfil_sec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExfilDomainsLength.ProtoReflect.Descriptor instead.
func (*ExfilDomainsLength) Descriptor() ([]byte, []int) {
	return file_exfil_sec_proto_rawDescGZIP(), []int{3}
}

func (x *ExfilDomainsLength) GetLen() int64 {
	if x != nil {
		return x.Len
	}
	return 0
}

var File_exfil_sec_proto protoreflect.FileDescriptor

const file_exfil_sec_proto_rawDesc = "" +
	"\n" +
	"\x0fexfil_sec.proto\x12\fexfil_kernel\"\xa0\x02\n" +
	"\fExfilDomains\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x10\n" +
	"\x03tld\x18\x02 \x01(\tR\x03tld\x12 \n" +
	"\vtotalLength\x18\x03 \x01(\x03R\vtotalLength\x12&\n" +
	"\x0efeatureVectors\x18\x04 \x03(\rR\x0efeatureVectors\x12>\n" +
	"\x06status\x18\x05 \x03(\v2&.exfil_kernel.ExfilDomains.StatusEntryR\x06status\x1a\\\n" +
	"\vStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\x0e2!.exfil_kernel.DNS_MALICIOUS_FLAGSR\x05value:\x028\x01\"p\n" +
	"\fElfSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\fR\tpublicKey\x12$\n" +
	"\rsignatureHash\x18\x03 \x01(\fR\rsignatureHash\"\xe5\x01\n" +
	"\x1aExfillSecurityLengthLimits\x12|\n" +
	"\x16domainrangeExfilLimits\x18\x01 \x03(\v2D.exfil_kernel.ExfillSecurityLengthLimits.DomainrangeExfilLimitsEntryR\x16domainrangeExfilLimits\x1aI\n" +
	"\x1bDomainrangeExfilLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"&\n" +
	"\x12ExfilDomainsLength\x12\x10\n" +
	"\x03len\x18\x01 \x01(\x03R\x03len*4\n" +
	"\x13DNS_MALICIOUS_FLAGS\x12\r\n" +
	"\tMALICIOUS\x10\x00\x12\x0e\n" +
	"\n" +
	"SUSPICIOUS\x10\x012\xa3\x02\n" +
	"\x10NodeAgentService\x12K\n" +
	"\x0fGetExfilDomains\x12\x1a.exfil_kernel.ExfilDomains\x1a\x1a.exfil_kernel.ExfilDomains0\x01\x12U\n" +
	"\x15GenExfilDomainsLength\x12\x1a.exfil_kernel.ExfilDomains\x1a .exfil_kernel.ExfilDomainsLength\x12k\n" +
	"\x11BidirstreamLimits\x12(.exfil_kernel.ExfillSecurityLengthLimits\x1a(.exfil_kernel.ExfillSecurityLengthLimits(\x010\x01B9Z7github.com/Synarcs/Data-Exfiltration-Security-Frameworkb\x06proto3"

var (
	file_exfil_sec_proto_rawDescOnce sync.Once
	file_exfil_sec_proto_rawDescData []byte
)

func file_exfil_sec_proto_rawDescGZIP() []byte {
	file_exfil_sec_proto_rawDescOnce.Do(func() {
		file_exfil_sec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exfil_sec_proto_rawDesc), len(file_exfil_sec_proto_rawDesc)))
	})
	return file_exfil_sec_proto_rawDescData
}

var file_exfil_sec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exfil_sec_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_exfil_sec_proto_goTypes = []any{
	(DNS_MALICIOUS_FLAGS)(0),           // 0: exfil_kernel.DNS_MALICIOUS_FLAGS
	(*ExfilDomains)(nil),               // 1: exfil_kernel.ExfilDomains
	(*ElfSignature)(nil),               // 2: exfil_kernel.ElfSignature
	(*ExfillSecurityLengthLimits)(nil), // 3: exfil_kernel.ExfillSecurityLengthLimits
	(*ExfilDomainsLength)(nil),         // 4: exfil_kernel.ExfilDomainsLength
	nil,                                // 5: exfil_kernel.ExfilDomains.StatusEntry
	nil,                                // 6: exfil_kernel.ExfillSecurityLengthLimits.DomainrangeExfilLimitsEntry
}
var file_exfil_sec_proto_depIdxs = []int32{
	5, // 0: exfil_kernel.ExfilDomains.status:type_name -> exfil_kernel.ExfilDomains.StatusEntry
	6, // 1: exfil_kernel.ExfillSecurityLengthLimits.domainrangeExfilLimits:type_name -> exfil_kernel.ExfillSecurityLengthLimits.DomainrangeExfilLimitsEntry
	0, // 2: exfil_kernel.ExfilDomains.StatusEntry.value:type_name -> exfil_kernel.DNS_MALICIOUS_FLAGS
	1, // 3: exfil_kernel.NodeAgentService.GetExfilDomains:input_type -> exfil_kernel.ExfilDomains
	1, // 4: exfil_kernel.NodeAgentService.GenExfilDomainsLength:input_type -> exfil_kernel.ExfilDomains
	3, // 5: exfil_kernel.NodeAgentService.BidirstreamLimits:input_type -> exfil_kernel.ExfillSecurityLengthLimits
	1, // 6: exfil_kernel.NodeAgentService.GetExfilDomains:output_type -> exfil_kernel.ExfilDomains
	4, // 7: exfil_kernel.NodeAgentService.GenExfilDomainsLength:output_type -> exfil_kernel.ExfilDomainsLength
	3, // 8: exfil_kernel.NodeAgentService.BidirstreamLimits:output_type -> exfil_kernel.ExfillSecurityLengthLimits
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_exfil_sec_proto_init() }
func file_exfil_sec_proto_init() {
	if File_exfil_sec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exfil_sec_proto_rawDesc), len(file_exfil_sec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exfil_sec_proto_goTypes,
		DependencyIndexes: file_exfil_sec_proto_depIdxs,
		EnumInfos:         file_exfil_sec_proto_enumTypes,
		MessageInfos:      file_exfil_sec_proto_msgTypes,
	}.Build()
	File_exfil_sec_proto = out.File
	file_exfil_sec_proto_goTypes = nil
	file_exfil_sec_proto_depIdxs = nil
}
