syntax = "proto3";

package exfil_kernel;

option go_package = "github.com/Synarcs/Data-Exfiltration-Security-Framework";

// the proto is initially written for multi-layer security with control plane verifying progs, and signatures for the eBPF progs at the endpoint over the data plane

enum DNS_MALICIOUS_FLAGS {
    MALICIOUS  = 0;
    SUSPICIOUS = 1;
}

message ExfilDomains {
    string domain = 1;
    string tld = 2;
    int64 totalLength = 3;
    repeated uint32 featureVectors = 4;
    map<string, DNS_MALICIOUS_FLAGS> status = 5;
};


message ElfSignature { 
    bytes signature = 1;
    bytes publicKey = 2;
    bytes signatureHash = 3;
}

message ExfillSecurityLengthLimits { 
    map<int32, int32> domainrangeExfilLimits = 1;
}

message ExfilDomainsLength {
    int64 len = 1;
}

service NodeAgentService {
    rpc GetExfilDomains(ExfilDomains) returns (stream ExfilDomains);
    rpc GenExfilDomainsLength(ExfilDomains) returns (ExfilDomainsLength);
    rpc BidirstreamLimits(stream ExfillSecurityLengthLimits) returns (stream ExfillSecurityLengthLimits);
};
