# load the controller config 

controller:
  # use this to further expose the stream controller api endpoints for dynamic threat inferencing 
  port: 8080
  localTestBench: true # a local test set up for infrastructure with custom local zones use fixed static ipv4 addresses only 

k8s:
  enabled: false
  k8sAdvertisedHostServiceAddress: ""
  cni:
    name: ""
    l7FilterSupport: "" # envoy
    l3FilterSupport: ""  # ipvs, iptables, ebpf over vxlan host 


streamConfig:
  host: "10.158.82.6"
  brokerPort: 9092 
  schemaRegistry:
    host: "10.158.82.6"
    port: 8081
  
  streamThreatTopic: "exfil-sec"
  streamThreatTopicInferState: "exfil-sec-infer-controller"  # only udp from the  data plane will be injected into the topic 
  recursorTCPTransportMaliciousTopic: "exfil-sec-infer-controller-tcp" 

  consumerGroupName: "exfil_dns_sec"