// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: exfil_sec_inference.proto

package exfil_sec_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_exfil_sec_inference_proto protoreflect.FileDescriptor

const file_exfil_sec_inference_proto_rawDesc = "" +
	"\n" +
	"\x19exfil_sec_inference.proto\x12\fexfil_kernelBUZSgithub.com/Synarcs/Data-Exfiltration-Security-Framework/exfil_sec_api;exfil_sec_apib\x06proto3"

var file_exfil_sec_inference_proto_goTypes = []any{}
var file_exfil_sec_inference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exfil_sec_inference_proto_init() }
func file_exfil_sec_inference_proto_init() {
	if File_exfil_sec_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exfil_sec_inference_proto_rawDesc), len(file_exfil_sec_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exfil_sec_inference_proto_goTypes,
		DependencyIndexes: file_exfil_sec_inference_proto_depIdxs,
	}.Build()
	File_exfil_sec_inference_proto = out.File
	file_exfil_sec_inference_proto_goTypes = nil
	file_exfil_sec_inference_proto_depIdxs = nil
}
