// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: exfil_sec_inference.proto

package exfil_sec_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DNSOnnxInferenceService_IngressInfer_FullMethodName = "/exfil_kernel.DNSOnnxInferenceService/IngressInfer"
	DNSOnnxInferenceService_EgressInfer_FullMethodName  = "/exfil_kernel.DNSOnnxInferenceService/EgressInfer"
	DNSOnnxInferenceService_VersionInfo_FullMethodName  = "/exfil_kernel.DNSOnnxInferenceService/VersionInfo"
)

// DNSOnnxInferenceServiceClient is the client API for DNSOnnxInferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DNSOnnxInferenceServiceClient interface {
	IngressInfer(ctx context.Context, in *DnsInferenceRequest, opts ...grpc.CallOption) (*DnsInferenceResponseIngress, error)
	EgressInfer(ctx context.Context, in *DnsInferenceRequest, opts ...grpc.CallOption) (*DnsInferenceResponseEgress, error)
	VersionInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceHeartBeatVersion, error)
}

type dNSOnnxInferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSOnnxInferenceServiceClient(cc grpc.ClientConnInterface) DNSOnnxInferenceServiceClient {
	return &dNSOnnxInferenceServiceClient{cc}
}

func (c *dNSOnnxInferenceServiceClient) IngressInfer(ctx context.Context, in *DnsInferenceRequest, opts ...grpc.CallOption) (*DnsInferenceResponseIngress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsInferenceResponseIngress)
	err := c.cc.Invoke(ctx, DNSOnnxInferenceService_IngressInfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSOnnxInferenceServiceClient) EgressInfer(ctx context.Context, in *DnsInferenceRequest, opts ...grpc.CallOption) (*DnsInferenceResponseEgress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsInferenceResponseEgress)
	err := c.cc.Invoke(ctx, DNSOnnxInferenceService_EgressInfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSOnnxInferenceServiceClient) VersionInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceHeartBeatVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceHeartBeatVersion)
	err := c.cc.Invoke(ctx, DNSOnnxInferenceService_VersionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSOnnxInferenceServiceServer is the server API for DNSOnnxInferenceService service.
// All implementations should embed UnimplementedDNSOnnxInferenceServiceServer
// for forward compatibility.
type DNSOnnxInferenceServiceServer interface {
	IngressInfer(context.Context, *DnsInferenceRequest) (*DnsInferenceResponseIngress, error)
	EgressInfer(context.Context, *DnsInferenceRequest) (*DnsInferenceResponseEgress, error)
	VersionInfo(context.Context, *emptypb.Empty) (*ServiceHeartBeatVersion, error)
}

// UnimplementedDNSOnnxInferenceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSOnnxInferenceServiceServer struct{}

func (UnimplementedDNSOnnxInferenceServiceServer) IngressInfer(context.Context, *DnsInferenceRequest) (*DnsInferenceResponseIngress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngressInfer not implemented")
}
func (UnimplementedDNSOnnxInferenceServiceServer) EgressInfer(context.Context, *DnsInferenceRequest) (*DnsInferenceResponseEgress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EgressInfer not implemented")
}
func (UnimplementedDNSOnnxInferenceServiceServer) VersionInfo(context.Context, *emptypb.Empty) (*ServiceHeartBeatVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionInfo not implemented")
}
func (UnimplementedDNSOnnxInferenceServiceServer) testEmbeddedByValue() {}

// UnsafeDNSOnnxInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSOnnxInferenceServiceServer will
// result in compilation errors.
type UnsafeDNSOnnxInferenceServiceServer interface {
	mustEmbedUnimplementedDNSOnnxInferenceServiceServer()
}

func RegisterDNSOnnxInferenceServiceServer(s grpc.ServiceRegistrar, srv DNSOnnxInferenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedDNSOnnxInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSOnnxInferenceService_ServiceDesc, srv)
}

func _DNSOnnxInferenceService_IngressInfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DnsInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSOnnxInferenceServiceServer).IngressInfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSOnnxInferenceService_IngressInfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSOnnxInferenceServiceServer).IngressInfer(ctx, req.(*DnsInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSOnnxInferenceService_EgressInfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DnsInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSOnnxInferenceServiceServer).EgressInfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSOnnxInferenceService_EgressInfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSOnnxInferenceServiceServer).EgressInfer(ctx, req.(*DnsInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSOnnxInferenceService_VersionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSOnnxInferenceServiceServer).VersionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSOnnxInferenceService_VersionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSOnnxInferenceServiceServer).VersionInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSOnnxInferenceService_ServiceDesc is the grpc.ServiceDesc for DNSOnnxInferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSOnnxInferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exfil_kernel.DNSOnnxInferenceService",
	HandlerType: (*DNSOnnxInferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngressInfer",
			Handler:    _DNSOnnxInferenceService_IngressInfer_Handler,
		},
		{
			MethodName: "EgressInfer",
			Handler:    _DNSOnnxInferenceService_EgressInfer_Handler,
		},
		{
			MethodName: "VersionInfo",
			Handler:    _DNSOnnxInferenceService_VersionInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exfil_sec_inference.proto",
}
