@startuml
!pragma teoz true
' Set the skin parameters
skinparam rectangle {
  BackgroundColor White
  BorderColor Black
}

box "Remote Trust Infrastructure" #LightBlue
  participant Controller
end box

box "Endpoint in Data Plane\n" #LightSalmon
  participant "eBPF Loader\n(Node Agent)" as Loader
  participant "Kernel Keyring" as Keyring
  participant "Kernel (LSM Hook)\n (BPF_PROG-)" as Kernel
end box

== mTLS Handshake ==
Loader -> Controller : Controller Cert request
Controller -> Loader : Server cert + eBPF Loader cert requests
Loader -> Controller : eBPF Loader certificate + session key
Controller -> Controller : Verify eBPF Loader certificate
Loader -> Loader  : Verify controller certificate 
Controller -> Loader : gRPC over mTLS established

== gRPC Signing Request ==
Loader -> Loader : Read compiled eBPF rawcode
Loader -> Controller : Request to sign eBPF program over mTLS
Controller -> Controller : Sign eBPF binary + metadata
Controller -> Loader : Return signed eBPF bytecode + certificate

== Start Self Sign PKI == 
Loader -> Loader : Start Local CA
Loader -> Loader : Generate ephemeral ECDSA key

== Sign eBPF JIT bytecode ==
Loader -> Loader : libbpf JIT eBPF code
Loader -> Loader : Generate Sign-Request on behalf of JIT eBPF code
Loader -> Loader : Combine JIT eBPF code with controller-signed cert
Loader -> Loader : Sign the combined payload
Loader -> Loader : Get Signed Cert
' Loader -> Loader : Bind cert to process (session keying)

== Process Keyring Injection ==
Loader -> Keyring : Store controller-signed cert (raw eBPF code)
Loader -> Keyring : Store ephemeral cert  (JIT eBPF code)

== Injection and Enforcement ==
Loader -> Kernel : syscall: bpf_prog_load()
Kernel -> Keyring : Fetch keys from process keyring
Kernel -> Kernel : Verify controller cert 
Kernel -> Kernel : Verify ephemeral cert
Kernel -> Kernel : Enforce via LSM hook (allow/deny)

@enduml