FROM python:2.7.18 as base_exf 

# put all the legacy raw exfiltration tools running over python2.7 

ARG port=53 

RUN apt-get update && apt-get install -y dnsutils libpcap-dev vim
RUN git clone https://github.com/sensepost/DET.git


WORKDIR DET
RUN pip install -r requirements.txt 

EXPOSE 53/udp 5353/udp 143/udp 1232/udp 5000/udp 


