FROM python:2.7.18 as base_exf 

# put all the legacy raw exfiltration tools running over python2.7 


RUN git clone https://github.com/Arno0x/DNSExfiltrator.git

WORKDIR DNSExfiltrator

RUN cd DNSExfiltrator && pip install -r requirements.txt && python dnsexfiltrator.py -d t.bleed.io -p complex

EXPOSE 53 
